//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Products
    {
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public string Description { get; set; }
        [DataMember]
        public decimal Price { get; set; }
        [DataMember]
        public float Stock { get; set; }
        [DataMember]
        public System.DateTime LastBuy { get; set; }
        [DataMember]
        public string Remarks { get; set; }
        [DataMember]
        public Nullable<float> Quantity { get; set; }
        [IgnoreDataMember]
        public string Discriminator { get; set; }
    }
}
